import React, { useState } from 'react';
import './AnimationPrize.css';
import AnimationPrizeBadge from './AnimationPrizeBadge';
import ReactConfetti from 'react-confetti';
import { Button } from 'antd';

const svg = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
            data-stacking-context="true" aria-owns="badge-svg" width="300" height="300"
            viewBox="613.9000244140625 253.60000610351562 300 300"><!-- Generated by dom-to-svg from
            http://localhost:5173/gamification/rules/new -->
            <style />
      <g data-stacking-layer="rootBackgroundAndBorders" />
      <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
      <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
      <g data-stacking-layer="nonPositionedFloats" />
      <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
      <g
            data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
      <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
      <g data-tag="div" id="badge-svg"
            class="flex flex-col justify-center items-center relative min-w-[300px] min-h-[300px]"
            data-z-index="auto" data-stacking-context="true" aria-owns="div1 div2 svg5 mt-[20%]1">
            <g data-stacking-layer="childStackingContextsWithPositiveStackLevels">
                  <g data-tag="div" id="mt-[20%]1" class="mt-[20%]" data-z-index="10"
                        data-stacking-context="true" aria-owns="svg6">
                        <g data-tag="svg" id="svg6" data-z-index="auto" data-stacking-context="true"
                              mask="url(#mask-for-svg61)">
                              <g data-stacking-layer="rootBackgroundAndBorders" />
                              <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
                              <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
                              <g data-stacking-layer="nonPositionedFloats" />
                              <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
                              <g
                                    data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
                              <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
                              <mask id="mask-for-svg61">
                                    <rect width="160" height="160" x="683.9000244140625"
                                          y="350.20001220703125" fill="#ffffff" />
                              </mask>
                              <g class="svg-content" data-view-box="0 0 200 200" data-width="160"
                                    data-height="160" transform="matrix(0.8 0 0 0.8 683.9 350.2)">
                                    <path fill="rgb(71, 79, 127)" fill-rule="evenodd"
                                          d="M169.909 139.373c-8.173-9.433-9.501-24.163-4.077-35.403C170.425 94.452 173 83.777 173 72.5 173 32.46 140.541 0 100.5 0 60.46 0 28 32.46 28 72.5c0 11.022 2.46 21.47 6.86 30.824 5.312 11.293 3.84 26.01-4.425 35.362-10.252 11.602-17.642 25.792-21.063 41.465C7.016 190.942 16.194 200 27.24 200h145.263c11.046 0 20.225-9.057 17.869-19.849-3.355-15.365-10.523-29.306-20.463-40.778Z"
                                          clip-rule="evenodd" color="rgba(0, 0, 0, 0.88)"
                                          stroke="none" />
                                    <defs color="rgba(0, 0, 0, 0.88)" fill="none" stroke="none">
                                          <linearGradient id="svg6-paint0_linear_133_29" x1="99.872"
                                                x2="99.872" y1="0" y2="200"
                                                gradientUnits="userSpaceOnUse">
                                                <stop stop-color="#B8DBFC" />
                                                <stop offset="1" stop-color="#F8FBFE" />
                                          </linearGradient>
                                    </defs>
                              </g>
                        </g>
                  </g>
                  <g data-tag="div" id="div2" data-z-index="15" data-stacking-context="true"
                        aria-owns="svg4">
                        <g data-tag="svg" id="svg4" data-z-index="auto" data-stacking-context="true"
                              mask="url(#mask-for-svg41)">
                              <g data-stacking-layer="rootBackgroundAndBorders" />
                              <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
                              <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
                              <g data-stacking-layer="nonPositionedFloats" />
                              <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
                              <g
                                    data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
                              <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
                              <mask id="mask-for-svg41">
                                    <rect width="220" height="220" x="653.9000244140625"
                                          y="290.20001220703125" fill="#ffffff" />
                              </mask>
                              <g class="svg-content" data-view-box="0 0 51 42" data-width="220"
                                    data-height="220"
                                    transform="matrix(4.31373 0 0 4.31373 653.9 309.612)">
                                    <path fill="rgb(251, 175, 81)"
                                          d="M50.1 31.9c0 .5-3.1.5-3.3 1-.2.5 2.3 2.4 2 2.8-.3.4-2.9-1.3-3.3-.9-.4.3.7 3.3.2 3.5-3.2 1.1-7.2-1-10.5-.4s-6.4 3.9-9.7 3.9c-3.3 0-6.4-3.4-9.7-3.9-3.3-.6-7.3 1.6-10.5.4-.5-.2.6-3.1.2-3.5-.4-.3-3 1.3-3.3.9-.3-.4 2.2-2.3 2-2.8-.2-.5-3.3-.5-3.3-1 0-1.8 3.1-3.5 3.1-5.3C4 24.8.9 23.1.9 21.3.9 19.5 4 17.8 4 16 4 14.2.9 12.5.9 10.7c0-.5 3.1-.5 3.3-1 .2-.5-2.3-2.4-2-2.8.3-.4 2.9 1.3 3.3.9.4-.3-.7-3.3-.2-3.5 3.2-1.1 7.2 1 10.5.4S22.2.8 25.5.8c3.3 0 6.4 3.4 9.7 3.9 3.3.6 7.3-1.6 10.5-.4.5.2-.6 3.1-.2 3.5.4.3 3-1.3 3.3-.9.3.4-2.2 2.3-2 2.8.2.5 3.3.5 3.3 1 0 1.8-3.1 3.5-3.1 5.3 0 1.8 3.1 3.5 3.1 5.3 0 1.8-3.1 3.5-3.1 5.3 0 1.8 3.1 3.6 3.1 5.3Z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <defs color="rgba(0, 0, 0, 0.88)" fill="none" stroke="none">
                                          <linearGradient id="svg4-SvgjsLinearGradient1011">
                                                <stop stop-color="#fbc2eb" offset="0" />
                                                <stop stop-color="#a6c1ee" offset="1" />
                                          </linearGradient>
                                    </defs>
                              </g>
                        </g>
                  </g>
                  <g data-tag="div" id="div1" data-z-index="20" data-stacking-context="true"
                        aria-owns="svg1 svg2 svg3">
                        <g data-tag="svg" id="svg1" data-z-index="auto" data-stacking-context="true"
                              mask="url(#mask-for-svg11)">
                              <g data-stacking-layer="rootBackgroundAndBorders" />
                              <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
                              <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
                              <g data-stacking-layer="nonPositionedFloats" />
                              <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
                              <g
                                    data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
                              <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
                              <mask id="mask-for-svg11">
                                    <rect width="200" height="200" x="663.9000244140625"
                                          y="303.6000061035156" fill="#ffffff" />
                              </mask>
                              <g class="svg-content" data-view-box="0 0 53 53" data-width="100%"
                                    data-height="100%"
                                    transform="matrix(3.77358 0 0 3.77358 663.9 303.6)">
                                    <path fill="rgb(206, 53, 95)"
                                          d="M52.1 26.5c0 3.2-4.3 5.6-5.5 8.4-1.2 2.9.1 7.6-2.1 9.8-2.2 2.2-6.9.9-9.8 2.1-2.8 1.2-5.2 5.5-8.4 5.5s-5.6-4.3-8.4-5.5c-2.9-1.2-7.6.1-9.8-2.1-2.2-2.2-.9-6.9-2.1-9.8C4.8 32.1.5 29.7.5 26.5s4.3-5.6 5.5-8.4c1.2-2.9-.1-7.6 2.1-9.8 2.2-2.2 6.9-.9 9.8-2.1C20.7 5 23.1.7 26.3.7s5.6 4.3 8.4 5.5c2.9 1.2 7.6-.1 9.8 2.1 2.2 2.2.9 6.9 2.1 9.8 1.2 2.8 5.5 5.2 5.5 8.4Z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <defs color="rgba(0, 0, 0, 0.88)" fill="none" stroke="none">
                                          <linearGradient id="svg1-SvgjsLinearGradient1025">
                                                <stop stop-color="#f5f7fa" offset="0" />
                                                <stop stop-color="#c3cfe2" offset="1" />
                                          </linearGradient>
                                    </defs>
                              </g>
                        </g>
                        <g data-tag="svg" id="svg2" data-z-index="auto" data-stacking-context="true"
                              mask="url(#mask-for-svg21)">
                              <g data-stacking-layer="rootBackgroundAndBorders" />
                              <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
                              <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
                              <g data-stacking-layer="nonPositionedFloats" />
                              <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
                              <g
                                    data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
                              <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
                              <mask id="mask-for-svg21">
                                    <rect width="190" height="190" x="668.9000244140625"
                                          y="308.6000061035156" fill="#ffffff" />
                              </mask>
                              <g class="svg-content" data-view-box="0 0 53 53" data-width="95%"
                                    data-height="95%"
                                    transform="matrix(3.58491 0 0 3.58491 668.9 308.6)">
                                    <path fill="rgb(255, 206, 248)"
                                          d="M52.1 26.5c0 3.2-4.3 5.6-5.5 8.4-1.2 2.9.1 7.6-2.1 9.8-2.2 2.2-6.9.9-9.8 2.1-2.8 1.2-5.2 5.5-8.4 5.5s-5.6-4.3-8.4-5.5c-2.9-1.2-7.6.1-9.8-2.1-2.2-2.2-.9-6.9-2.1-9.8C4.8 32.1.5 29.7.5 26.5s4.3-5.6 5.5-8.4c1.2-2.9-.1-7.6 2.1-9.8 2.2-2.2 6.9-.9 9.8-2.1C20.7 5 23.1.7 26.3.7s5.6 4.3 8.4 5.5c2.9 1.2 7.6-.1 9.8 2.1 2.2 2.2.9 6.9 2.1 9.8 1.2 2.8 5.5 5.2 5.5 8.4Z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                              </g>
                        </g>
                        <g data-tag="svg" id="svg3" data-z-index="auto" data-stacking-context="true"
                              mask="url(#mask-for-svg31)">
                              <g data-stacking-layer="rootBackgroundAndBorders" />
                              <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
                              <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
                              <g data-stacking-layer="nonPositionedFloats" />
                              <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
                              <g
                                    data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
                              <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
                              <mask id="mask-for-svg31">
                                    <rect width="160" height="160" x="683.9000244140625"
                                          y="323.6000061035156" fill="#ffffff" />
                              </mask>
                              <g class="svg-content" data-view-box="0 0 53 53" data-width="80%"
                                    data-height="80%"
                                    transform="matrix(3.01887 0 0 3.01887 683.9 323.6)">
                                    <defs color="rgba(0, 0, 0, 0.88)" fill="none" stroke="none">
                                          <linearGradient id="svg3-gradient" x1="0%" y1="0%"
                                                x2="100%" y2="0%">
                                                <stop offset="0%"
                                                      style="stop-color: rgb(255, 104, 146);" />
                                                <stop offset="100%"
                                                      style="stop-color: rgb(255, 155, 197);" />
                                          </linearGradient>
                                    </defs>
                                    <path fill="rgb(255, 104, 146)"
                                          d="M52.1 26.5c0 3.2-4.3 5.6-5.5 8.4-1.2 2.9.1 7.6-2.1 9.8-2.2 2.2-6.9.9-9.8 2.1-2.8 1.2-5.2 5.5-8.4 5.5s-5.6-4.3-8.4-5.5c-2.9-1.2-7.6.1-9.8-2.1-2.2-2.2-.9-6.9-2.1-9.8C4.8 32.1.5 29.7.5 26.5s4.3-5.6 5.5-8.4c1.2-2.9-.1-7.6 2.1-9.8 2.2-2.2 6.9-.9 9.8-2.1C20.7 5 23.1.7 26.3.7s5.6 4.3 8.4 5.5c2.9 1.2 7.6-.1 9.8 2.1 2.2 2.2.9 6.9 2.1 9.8 1.2 2.8 5.5 5.2 5.5 8.4Z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                              </g>
                        </g>
                  </g>
                  <g data-tag="svg" id="svg5" data-z-index="25" data-stacking-context="true"
                        mask="url(#mask-for-svg51)">
                        <g data-stacking-layer="rootBackgroundAndBorders" />
                        <g data-stacking-layer="childStackingContextsWithNegativeStackLevels" />
                        <g data-stacking-layer="inFlowNonInlineNonPositionedDescendants" />
                        <g data-stacking-layer="nonPositionedFloats" />
                        <g data-stacking-layer="inFlowInlineLevelNonPositionedDescendants" />
                        <g
                              data-stacking-layer="childStackingContextsWithStackLevelZeroAndPositionedDescendantsWithStackLevelZero" />
                        <g data-stacking-layer="childStackingContextsWithPositiveStackLevels" />
                        <mask id="mask-for-svg51">
                              <rect width="100" height="100" x="713.9000244140625"
                                    y="364.1000061035156" fill="#ffffff" />
                        </mask>
                        <g class="svg-content" data-view-box="0 0 100 125" data-width="100"
                              data-height="100" transform="matrix(0.8 0 0 0.8 723.9 364.1)">
                              <g display="none" color="rgba(0, 0, 0, 0.88)" fill="rgb(0, 0, 0)"
                                    stroke="none">
                                    <rect x="-1084.011" y="-126.52" display="inline"
                                          fill="rgb(0, 0, 0)" stroke="rgb(255, 255, 255)"
                                          stroke-linecap="round" stroke-linejoin="round"
                                          stroke-miterlimit="10" width="1216.349" height="602.747"
                                          color="rgba(0, 0, 0, 0.88)" />
                              </g>
                              <g color="rgba(0, 0, 0, 0.88)" fill="rgb(0, 0, 0)" stroke="none">
                                    <path fill="rgb(251, 175, 81)"
                                          d="M9.722,68.882c0.746-0.985,1.429-2.002,2.048-3.044c-1.194-0.307-2.397-0.545-3.604-0.71   C8.624,66.409,9.144,67.662,9.722,68.882z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M31.125,90.29c1.224,0.581,2.481,1.102,3.764,1.561c-0.165-1.207-0.404-2.414-0.713-3.615   C33.119,88.859,32.1,89.544,31.125,90.29z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M6.217,42.281c-0.467,2.504-0.702,5.104-0.702,7.735s0.235,5.23,0.7,7.725c0.209,1.231,0.897,3.232,0.897,3.232   c2.184,0.197,4.37,0.612,6.521,1.222c1.625-3.804,2.479-7.988,2.479-12.209c0-4.27-0.834-8.359-2.477-12.181   c-2.156,0.612-4.341,1.026-6.524,1.223C7.111,39.029,6.425,41.031,6.217,42.281z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M50,83.904c-4.27,0-8.359,0.834-12.18,2.477c0.614,2.163,1.029,4.348,1.223,6.526c0,0,2.005,0.687,3.224,0.894   c5.003,0.932,10.47,0.931,15.459,0.001c1.252-0.209,3.262-0.895,3.262-0.895c0.194-2.178,0.609-4.365,1.222-6.524   C58.406,84.758,54.221,83.904,50,83.904z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M15.661,67.107c-1.063,1.898-2.311,3.728-3.735,5.452c0,0,0.878,1.885,1.638,2.949c2.989,4.307,6.669,7.986,10.939,10.941   c1.062,0.758,2.941,1.653,2.941,1.653c1.699-1.427,3.533-2.681,5.465-3.754c-1.564-3.877-3.875-7.366-6.89-10.381   C23.003,70.974,19.523,68.672,15.661,67.107z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M90.281,31.136c-0.726,0.955-1.402,1.966-2.026,3.024c1.162,0.294,2.355,0.524,3.574,0.687   C91.372,33.574,90.854,32.336,90.281,31.136z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M50,16.098c4.221,0,8.407-0.854,12.21-2.479c-0.613-2.162-1.028-4.347-1.222-6.524l0.539-0.048   c-1.287-0.343-2.546-0.638-3.791-0.846C55.231,5.737,52.632,5.501,50,5.501c-2.633,0-5.231,0.235-7.725,0.7   c-1.226,0.208-3.232,0.895-3.232,0.895c-0.194,2.179-0.61,4.366-1.223,6.525C41.649,15.266,45.734,16.098,50,16.098z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M84.368,67.104c-3.875,1.561-7.365,3.865-10.393,6.869c-2.985,2.985-5.287,6.474-6.857,10.381   c1.9,1.064,3.731,2.313,5.455,3.737c0,0,1.91-0.923,2.921-1.639c4.275-2.986,7.955-6.667,10.94-10.94   c0.794-1.145,1.682-2.97,1.682-2.97C86.698,70.856,85.447,69.03,84.368,67.104z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M8.162,34.875c1.21-0.165,2.417-0.404,3.617-0.712c-0.625-1.058-1.315-2.081-2.069-3.065   C9.136,32.326,8.619,33.587,8.162,34.875z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M65.851,88.246c-0.308,1.195-0.546,2.396-0.71,3.598c1.253-0.452,2.503-0.97,3.745-1.557   C67.905,89.545,66.891,88.864,65.851,88.246z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M65.852,11.756c1.04-0.618,2.054-1.298,3.035-2.041c-1.241-0.586-2.492-1.105-3.745-1.557   C65.306,9.359,65.544,10.56,65.852,11.756z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M34.176,11.767c0.31-1.201,0.548-2.408,0.713-3.616c-1.285,0.459-2.541,0.981-3.765,1.561   C32.101,10.459,33.12,11.144,34.176,11.767z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M92.89,38.999c-2.237-0.201-4.412-0.605-6.496-1.191c-1.642,3.823-2.476,7.91-2.476,12.179   c0,4.22,0.854,8.405,2.477,12.207c2.05-0.578,4.217-0.989,6.472-1.217c0,0,0.708-1.993,0.917-3.227   c0.466-2.499,0.701-5.099,0.701-7.733s-0.235-5.234-0.699-7.725C93.575,41.026,92.89,38.999,92.89,38.999z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M24.51,13.55c-4.218,2.917-7.908,6.598-10.975,10.943c-0.737,1.063-1.649,2.909-1.649,2.909   c1.444,1.718,2.707,3.562,3.781,5.492c3.864-1.567,7.344-3.878,10.353-6.887c3.012-2.989,5.322-6.464,6.89-10.351   c-1.928-1.071-3.764-2.325-5.465-3.754C27.444,11.901,25.564,12.796,24.51,13.55z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M91.828,65.14c-1.228,0.174-2.418,0.408-3.568,0.701c0.62,1.044,1.299,2.051,2.036,3.013   C90.861,67.651,91.373,66.412,91.828,65.14z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M73.975,26c3.02,3.019,6.509,5.332,10.391,6.897c1.086-1.951,2.329-3.778,3.719-5.435c0,0-0.893-1.881-1.648-2.938   c-2.946-4.289-6.626-7.978-10.939-10.971c-1.014-0.718-2.925-1.642-2.925-1.642c-1.723,1.423-3.554,2.672-5.455,3.737   C68.688,19.559,70.989,23.038,73.975,26z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                                    <path fill="rgb(251, 175, 81)"
                                          d="M28.842,28.84c-3.319,3.319-7.156,5.886-11.42,7.653c1.782,4.238,2.69,8.769,2.69,13.493c0,4.664-0.93,9.294-2.695,13.521   c4.257,1.764,8.091,4.319,11.424,7.626c3.335,3.335,5.905,7.183,7.669,11.46c4.238-1.781,8.767-2.689,13.489-2.689   c4.662,0,9.29,0.929,13.516,2.692c1.77-4.305,4.33-8.151,7.636-11.457c3.346-3.319,7.192-5.877,11.458-7.636   c-1.762-4.225-2.692-8.853-2.692-13.517c0-4.718,0.906-9.245,2.689-13.489c-4.278-1.765-8.125-4.334-11.455-7.664   c-3.303-3.277-5.864-7.116-7.637-11.428c-4.225,1.762-8.853,2.692-13.515,2.692c-4.718,0-9.244-0.907-13.488-2.689   C34.742,21.7,32.172,25.537,28.842,28.84z"
                                          color="rgba(0, 0, 0, 0.88)" stroke="none" />
                              </g>
                        </g>
                  </g>
            </g>
      </g>
</svg>`;

const AnimatePrize = () => {
    const [isBadgeCollected, setIsBadgeCollected] = useState(false);

    const collectBadge = () => {
        setIsBadgeCollected(true);
    };

    return (
        <div className='w-[100svw] h-[100svh] bg-gray-100 flex justify-center items-center flex-col'>
          
            <AnimationPrizeBadge
                collected={isBadgeCollected}
                svgContent={svg}
            />
            <Button type='primary' onClick={collectBadge}>Collect Badge</Button>
        </div>
    );
};

export default AnimatePrize;
